# Generated by Django 5.0.4 on 2024-06-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='feedback',
        ),
    ]
