# Generated by Django 5.0.4 on 2024-06-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0005_otp_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='Admin',
            new_name='user',
        ),
    ]
