# Generated by Django 5.0.4 on 2024-06-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0006_rename_admin_otp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allinone.item')),
            ],
        ),
    ]
