# Generated by Django 5.0.4 on 2024-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0007_itemaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaccess',
            name='comment',
            field=models.TextField(default='Item denied'),
        ),
    ]
