# Generated by Django 5.0.4 on 2024-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0008_itemaccess_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
