# Generated by Django 5.0.4 on 2024-07-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0009_alter_admincategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='s_name',
            new_name='name',
        ),
    ]
