# Generated by Django 5.0.4 on 2024-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0010_rename_s_name_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Address',
            field=models.CharField(max_length=120),
        ),
    ]
