# Generated by Django 5.0.4 on 2024-07-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0011_alter_seller_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Address',
            new_name='address',
        ),
    ]
