# Generated by Django 5.0.4 on 2024-07-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0012_rename_address_seller_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
