# Generated by Django 5.0.4 on 2024-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0014_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
