# Generated by Django 5.0.4 on 2024-07-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0015_remove_otp_admin_remove_otp_seller_remove_otp_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name',
        ),
    ]
