# Generated by Django 5.0.4 on 2024-07-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0016_rename_u_name_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
    ]
