# Generated by Django 5.0.4 on 2024-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0018_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(default='images/p1.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/p1.png', upload_to='images/'),
        ),
    ]
