# Generated by Django 5.0.4 on 2024-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0019_alter_item_description_alter_item_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=900),
        ),
    ]
