# Generated by Django 5.0.4 on 2024-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0021_alter_itemaccess_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincategory',
            name='image',
            field=models.ImageField(default='images/p1.png', upload_to='images/'),
        ),
    ]
