# Generated by Django 5.0.4 on 2024-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0022_admincategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincategory',
            name='image',
            field=models.ImageField(default='images/p1.jpg', upload_to='images/'),
        ),
    ]
