# Generated by Django 5.0.4 on 2024-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0023_alter_admincategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
