# Generated by Django 5.0.4 on 2024-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0024_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=50),
        ),
    ]
