# Generated by Django 5.0.4 on 2024-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0026_remove_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
