# Generated by Django 5.0.4 on 2024-07-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0027_wishlist_is_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
