# Generated by Django 5.0.4 on 2024-07-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0028_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
